export default {
  UPDATE_CURRENT_TIME: 'UPDATE_CURRENT_TIME',
  SET_DEADLINE: 'SET_DEADLINE',
  CLEAR_DEADLINE: 'CLEAR_DEADLINE',
  SET_START: 'SET_START',
  CLEAR_START: 'CLEAR_START',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  SHOW_TIMERS: 'SHOW_TIMERS',
  HIDE_TIMERS: 'HIDE_TIMERS'
}
